# Generated by Django 4.2.7 on 2023-11-03 00:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('booking_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('depart_from', models.CharField(default=None)),
                ('destination', models.CharField(default=None)),
                ('departure', models.DateTimeField(default=None)),
                ('arrival', models.DateTimeField(default=None)),
                ('passenger', models.CharField(default=1)),
                ('airline_name', models.CharField(default=None, max_length=250)),
                ('stops', models.PositiveIntegerField(default=0)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Checkout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(default=None, max_length=250)),
                ('last_name', models.CharField(default=None, max_length=250)),
                ('middle_name', models.CharField(default=None, max_length=250)),
                ('nationality', models.CharField(default=None)),
                ('date_of_birth', models.DateField(default=None)),
                ('gender_male', models.CharField(blank=True, default=None, null=True)),
                ('gender_female', models.CharField(blank=True, default=None, null=True)),
                ('passport_no', models.CharField(default=None)),
                ('passport_expiry_date', models.DateField(default=None)),
                ('passport_issuing_authority', models.CharField(default=None)),
                ('contact', models.IntegerField()),
                ('mail', models.EmailField(max_length=254)),
                ('address', models.TextField()),
                ('seat_no', models.PositiveIntegerField(unique=True)),
                ('extra_luggage', models.CharField(default=0)),
                ('total_fare', models.DecimalField(decimal_places=2, max_digits=20)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('booking', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='booking.booking')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Flight_Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('awaiting_departure', models.BooleanField(blank=True, null=True)),
                ('trip_completed', models.BooleanField(blank=True, null=True)),
                ('trip_cancelled', models.BooleanField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('default', models.BooleanField(blank=True, null=True)),
                ('cheapest', models.BooleanField(blank=True, null=True)),
                ('time_saver', models.BooleanField(blank=True, null=True)),
                ('best', models.BooleanField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Trip_Round',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('one_way', models.BooleanField(blank=True, null=True)),
                ('round_trip', models.BooleanField(blank=True, null=True)),
                ('multi_trip', models.BooleanField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checkout', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.checkout')),
                ('flight_status', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='booking.flight_status')),
            ],
        ),
        migrations.AddField(
            model_name='booking',
            name='offer',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='booking.offer'),
        ),
        migrations.AddField(
            model_name='booking',
            name='round',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.trip_round'),
        ),
    ]
