# Generated by Django 4.2.7 on 2023-11-03 00:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Flight_Class',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('economy', models.BooleanField(blank=True, null=True)),
                ('business', models.BooleanField(blank=True, null=True)),
                ('first_class', models.BooleanField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='booking',
            name='flight_class',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='booking.flight_class'),
        ),
    ]
