# Generated by Django 4.2.7 on 2023-11-03 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_flight_class_booking_flight_class'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trip_round',
            name='multi_trip',
        ),
        migrations.AddField(
            model_name='booking',
            name='arrival_2',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='departure_2',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
