# Generated by Django 4.2.7 on 2023-11-04 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0004_airline_rename_booking_id_booking_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checkout',
            name='gender_female',
        ),
        migrations.RemoveField(
            model_name='checkout',
            name='gender_male',
        ),
        migrations.AddField(
            model_name='checkout',
            name='gender',
            field=models.CharField(default=None, max_length=25),
        ),
    ]
