# Generated by Django 4.2.7 on 2023-11-08 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0008_alter_location_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkout',
            name='seat_no',
            field=models.PositiveIntegerField(),
        ),
    ]
