# Generated by Django 4.2.7 on 2023-12-21 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0011_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkout',
            name='seat_no',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
