# Generated by Django 4.2.7 on 2023-12-24 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0012_alter_checkout_seat_no'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checkout',
            name='seat_no',
        ),
    ]
