# Generated by Django 4.2.7 on 2023-12-25 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0014_checkout_seat_no'),
    ]

    operations = [
        migrations.CreateModel(
            name='Flight_Letter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
    ]
