# Generated by Django 4.2.7 on 2023-12-26 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0018_rename_each_luggage_price_booking_each_extra_luggage_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkout',
            name='extra_luggage_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
    ]
